# Generated by Django 4.1.5 on 2023-10-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="testimonial")),
                ("name", models.CharField(max_length=50)),
                ("course", models.CharField(max_length=70)),
            ],
        ),
    ]
