# Generated by Django 4.1.5 on 2023-10-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Team", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="course",
            field=models.CharField(max_length=250),
        ),
    ]
