# Generated by Django 4.1.5 on 2023-10-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="aboutus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="about/")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("subjects", models.CharField(max_length=255)),
                ("course", models.CharField(max_length=255)),
                ("instructor", models.CharField(max_length=255)),
                ("students", models.CharField(max_length=255)),
            ],
        ),
    ]
