# Generated by Django 4.1.5 on 2023-10-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aboutus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="course",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="instructor",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="students",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="subjects",
            field=models.IntegerField(),
        ),
    ]
