# Generated by Django 4.1.5 on 2023-10-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OurCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="course/")),
                ("title", models.CharField(max_length=255)),
                ("instructor", models.CharField(max_length=255)),
                ("rating", models.FloatField(default=0.0)),
                ("num_reviws", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
            ],
        ),
    ]
