# Generated by Django 4.1.5 on 2023-10-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="course_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("image", models.ImageField(upload_to="detail/")),
                ("description", models.TextField()),
                ("instructor", models.TextField(max_length=250)),
                ("rating", models.FloatField()),
                ("lecture", models.IntegerField()),
                ("duration", models.FloatField()),
                ("skill", models.CharField(max_length=250)),
                ("language", models.CharField(max_length=250)),
                ("price", models.IntegerField()),
            ],
        ),
    ]
